#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Yuuki Koshiba
# SPDX-License-Identifier: BSD-3-Clause

import sys

y = 0.0
nums = [ float(e) for e in sys.argv[1:] ]
for x in nums:
    if x < 0:
        y += 1.0
print(y)
