#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Yuuki Koshiba
# SPDX-License-Identifier: BSD-3-Clause

import sys

har = 0

def tonum(s):
    try:
        return int(s)
    except:
        return float(s)

ans = 0

for line in sys.stdin:
        ans += tonum(line)
        har += 1

print(ans)
print(har)
